/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_marvel;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

/**
 *
 * @author Miguel Paz
 */
public class Batallas extends javax.swing.JFrame {

    /**
     * Creates new form Batallas
     */
    public Batallas() {
        initComponents();
         ImageIcon imagen= new ImageIcon("src\\Imagenes\\Para Frames\\Thor.jpg");
        //OBTENER TAMAÑO DEL FRAME
        Toolkit tk= Toolkit.getDefaultToolkit();
        Dimension tamaño= tk.getScreenSize();
        //Se le asigna el tamaño del frame al label
        jLabel2.setSize(tamaño);
     
        ImageIcon icono= new ImageIcon(imagen.getImage().getScaledInstance(jLabel2.getWidth(), jLabel2.getHeight(),Image.SCALE_DEFAULT));
        jLabel2.setIcon(icono);
       
     
        this.setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setLocation(0,0);
        this.setLocationRelativeTo(null);
        txtUA.setText(""+Player.playersActivos());
        txtUH.setText(""+Player.playersHistoricos());
        txtPJ.setText(""+Player.obtenerpartidasJugadas());
        txtGH.setText(""+Player.obtenerpartidasGanadasHeroes());
        txtGV.setText(""+Player.obtenerpartidasGanadasVillanos());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        txtGV = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtUA = new javax.swing.JLabel();
        txtPJ = new javax.swing.JLabel();
        txtUH = new javax.swing.JLabel();
        txtGH = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CANTIDAD DE USUARIOS ACTIVOS :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 180, 460, 29);

        txtGV.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txtGV.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtGV);
        txtGV.setBounds(550, 350, 100, 30);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CANTIDAD DE USUARIOS HISTÓRICOS :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 240, 490, 29);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("CANTIDAD DE PARTIDAS JUGADAS :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 120, 440, 29);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("GANADAS CON HEROES :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 300, 350, 29);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("GANADAS CON VILLANOS :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 350, 340, 30);

        txtUA.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txtUA.setForeground(new java.awt.Color(255, 255, 255));
        txtUA.setText("hola");
        getContentPane().add(txtUA);
        txtUA.setBounds(550, 180, 110, 20);

        txtPJ.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txtPJ.setForeground(new java.awt.Color(255, 255, 255));
        txtPJ.setText("jLabel3");
        getContentPane().add(txtPJ);
        txtPJ.setBounds(550, 120, 83, 29);

        txtUH.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txtUH.setForeground(new java.awt.Color(255, 255, 255));
        txtUH.setText("jLabel3");
        getContentPane().add(txtUH);
        txtUH.setBounds(550, 240, 83, 29);

        txtGH.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txtGH.setForeground(new java.awt.Color(255, 255, 255));
        txtGH.setText("jLabel3");
        getContentPane().add(txtGH);
        txtGH.setBounds(550, 300, 90, 29);

        jLabel1.setFont(new java.awt.Font("Arial", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BATALLAS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 10, 490, 60);

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 800, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Batallas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Batallas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Batallas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Batallas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Batallas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel txtGH;
    private javax.swing.JLabel txtGV;
    private javax.swing.JLabel txtPJ;
    private javax.swing.JLabel txtUA;
    private javax.swing.JLabel txtUH;
    // End of variables declaration//GEN-END:variables
}
