/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_marvel;

import java.awt.BorderLayout;
import java.awt.Dimension;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Miguel Paz
 */
public class Ultimosjuegos extends javax.swing.JFrame {
    ArrayList<String>partidas;

    /**
     * Creates new form Ultimosjuegos
     */
    public Ultimosjuegos() {
        initComponents();
        ImageIcon imagen= new ImageIcon("src\\Imagenes\\Para Frames\\BlackWidow.jpg");
        //OBTENER TAMAÑO DEL FRAME
        Toolkit tk= Toolkit.getDefaultToolkit();
        Dimension tamaño= tk.getScreenSize();
        //Se le asigna el tamaño del frame al label
        jLabel2.setSize(tamaño);
     
        ImageIcon icono= new ImageIcon(imagen.getImage().getScaledInstance(jLabel2.getWidth(), jLabel2.getHeight(),Image.SCALE_DEFAULT));
        jLabel2.setIcon(icono);
       
     
        this.setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setLocation(0,0);
        
        try{
        partidas=Player.existe(Player.getLoggedPlayer().getUsername()).partidas;
        } catch (IOException ex) {
            Logger.getLogger(Ultimosjuegos.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println("==========================================\n             MIS ULTIMOS JUEGOS               \n===="
                + "===============================================");
        for (String c: partidas){
            System.out.println(c);
            System.out.println("====================================================");
        }
        lastGame();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tableLastGame = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        tableLastGame.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tableLastGame.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableLastGame);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(4, 73, 670, 390);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MIS ÚLTIMAS PARTIDAS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 20, 680, 50);

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 900, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ultimosjuegos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Ultimosjuegos().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableLastGame;
    // End of variables declaration//GEN-END:variables
 
    private void lastGame(){
        String columnas[]={"MIS ULTIMOS JUEGOS"};
        String partida[][]=new String[partidas.size()][1];
        if(partidas.size()<20){
            for(int cont=0;cont<partida.length;cont++){
                partida[cont][0]=partidas.get(cont);
            }
        }else{
            for(int cont=0;cont<20;cont++){
                partida[cont][0]=partidas.get(cont);
            }
                    
        }
        DefaultTableModel model=new DefaultTableModel(partida,columnas);
        tableLastGame.setModel(model);
        this.setLayout(new BorderLayout());  
    }

}

